1870:
  lat: 53.55
  lon: -114.11
  name: EDMONTON STONY PLAIN UA
  province: Alberta
1873:
  lat: 53.68
  lon: -112.87
  name: ELK ISLAND NAT PARK
  province: Alberta
1881:
  lat: 52.97
  lon: -111.0
  name: FABYAN
  province: Alberta
1920:
  lat: 53.31
  lon: -110.07
  name: LLOYDMINSTER A
  province: Alberta
1977:
  lat: 53.51
  lon: -112.1
  name: VEGREVILLE
  province: Alberta
2173:
  lat: 50.73
  lon: -113.96
  name: OKOTOKS
  province: Alberta
2174:
  lat: 49.87
  lon: -112.79
  name: PICTURE BUTTE WEST
  province: Alberta
2180:
  lat: 50.56
  lon: -111.85
  name: BROOKS
  province: Alberta
2224:
  lat: 50.0
  lon: -113.64
  name: CLARESHOLM
  province: Alberta
2295:
  lat: 50.61
  lon: -112.98
  name: QUEENSTOWN
  province: Alberta
2832:
  lat: 54.42
  lon: -110.28
  name: COLD LAKE A
  province: Alberta
2855:
  lat: 50.37
  lon: -102.57
  name: BROADVIEW
  province: Saskatchewan
2925:
  lat: 50.55
  lon: -103.65
  name: INDIAN HEAD CDA
  province: Saskatchewan
2930:
  lat: 51.26
  lon: -103.75
  name: KELLIHER
  province: Saskatchewan
2942:
  lat: 51.42
  lon: -105.25
  name: LAST MOUNTAIN CS
  province: Saskatchewan
2947:
  lat: 52.0
  lon: -104.63
  name: LEROY
  province: Saskatchewan
3088:
  lat: 51.13
  lon: -106.58
  name: ELBOW CS
  province: Saskatchewan
3142:
  lat: 51.15
  lon: -107.26
  name: ROCK POINT
  province: Saskatchewan
3157:
  lat: 50.27
  lon: -107.73
  name: SWIFT CURRENT CDA
  province: Saskatchewan
3259:
  lat: 52.36
  lon: -108.83
  name: SCOTT CDA
  province: Saskatchewan
3318:
  lat: 51.48
  lon: -107.05
  name: OUTLOOK PFRA
  province: Saskatchewan
3460:
  lat: 49.93
  lon: -101.2
  name: ELKHORN 2 EAST
  province: Manitoba
3463:
  lat: 49.28
  lon: -99.29
  name: BALDUR
  province: Manitoba
3619:
  lat: 50.01
  lon: -97.81
  name: MARQUETTE
  province: Manitoba
3649:
  lat: 49.19
  lon: -98.9
  name: PILOT MOUND (AUT)
  province: Manitoba
3678:
  lat: 50.12
  lon: -97.17
  name: STONY MOUNTAIN
  province: Manitoba
3766:
  lat: 52.03
  lon: -100.65
  name: COWAN
  province: Manitoba
7485:
  lat: 49.44
  lon: -108.99
  name: EASTEND CYPRESS (AUT)
  province: Saskatchewan
8804:
  lat: 49.13
  lon: -112.05
  name: MILK RIVER
  province: Alberta
8993:
  lat: 51.08
  lon: -97.55
  name: FISHER BRANCH (AUT)
  province: Manitoba
10186:
  lat: 50.18
  lon: -96.06
  name: PINAWA
  province: Manitoba
10188:
  lat: 52.11
  lon: -101.23
  name: SWAN RIVER RCS
  province: Manitoba
10196:
  lat: 49.02
  lon: -95.6
  name: SPRAGUE
  province: Manitoba
10225:
  lat: 51.67
  lon: -110.21
  name: ESTHER 1
  province: Alberta
10660:
  lat: 51.77
  lon: -104.2
  name: WYNYARD (AUT)
  province: Saskatchewan
10666:
  lat: 49.7
  lon: -103.8
  name: WEYBURN
  province: Saskatchewan
10667:
  lat: 49.9
  lon: -109.47
  name: MAPLE CREEK
  province: Saskatchewan
10688:
  lat: 53.92
  lon: -106.07
  name: WASKESIU LAKE
  province: Saskatchewan
10725:
  lat: 49.12
  lon: -110.47
  name: ONEFOUR CDA
  province: Alberta
10727:
  lat: 52.82
  lon: -104.6
  name: MELFORT
  province: Saskatchewan
10784:
  lat: 51.57
  lon: -107.92
  name: ROSETOWN EAST
  province: Saskatchewan
10795:
  lat: 50.91
  lon: -109.5
  name: LEADER AIRPORT
  province: Saskatchewan
10805:
  lat: 49.73
  lon: -105.95
  name: ASSINIBOIA AIRPORT
  province: Saskatchewan
10821:
  lat: 49.06
  lon: -107.59
  name: VAL MARIE SOUTHEAST
  province: Saskatchewan
10881:
  lat: 50.5
  lon: -98.04
  name: OAKPOINT MARINE
  province: Manitoba
10884:
  lat: 49.9
  lon: -98.28
  name: PORTAGE SOUTHPORT
  province: Manitoba
10906:
  lat: 52.45
  lon: -113.76
  name: LACOMBE CDA 2
  province: Alberta
10915:
  lat: 49.73
  lon: -111.45
  name: BOW ISLAND
  province: Alberta
26857:
  lat: 49.5
  lon: -98.03
  name: CARMAN U OF M CS
  province: Manitoba
26866:
  lat: 51.1
  lon: -100.06
  name: DAUPHIN CS
  province: Manitoba
26888:
  lat: 52.83
  lon: -111.1
  name: 'WAINWRIGHT CFB AIRFIELD '
  province: Alberta
27741:
  lat: 49.91
  lon: -99.36
  name: CARBERRY CS
  province: Manitoba
