1870:
  lat: 53.55
  lon: -114.11
  name: EDMONTON STONY PLAIN UA
  province: Alberta
1881:
  lat: 52.97
  lon: -111.0
  name: FABYAN
  province: Alberta
1977:
  lat: 53.51
  lon: -112.1
  name: VEGREVILLE
  province: Alberta
2173:
  lat: 50.73
  lon: -113.96
  name: OKOTOKS
  province: Alberta
2180:
  lat: 50.56
  lon: -111.85
  name: BROOKS
  province: Alberta
2224:
  lat: 50.0
  lon: -113.64
  name: CLARESHOLM
  province: Alberta
2832:
  lat: 54.42
  lon: -110.28
  name: COLD LAKE A
  province: Alberta
2855:
  lat: 50.37
  lon: -102.57
  name: BROADVIEW
  province: Saskatchewan
2925:
  lat: 50.55
  lon: -103.65
  name: INDIAN HEAD CDA
  province: Saskatchewan
2930:
  lat: 51.26
  lon: -103.75
  name: KELLIHER
  province: Saskatchewan
2942:
  lat: 51.42
  lon: -105.25
  name: LAST MOUNTAIN CS
  province: Saskatchewan
2947:
  lat: 52.0
  lon: -104.63
  name: LEROY
  province: Saskatchewan
3142:
  lat: 51.15
  lon: -107.26
  name: ROCK POINT
  province: Saskatchewan
3157:
  lat: 50.27
  lon: -107.73
  name: SWIFT CURRENT CDA
  province: Saskatchewan
3259:
  lat: 52.36
  lon: -108.83
  name: SCOTT CDA
  province: Saskatchewan
3460:
  lat: 49.93
  lon: -101.2
  name: ELKHORN 2 EAST
  province: Manitoba
3463:
  lat: 49.28
  lon: -99.29
  name: BALDUR
  province: Manitoba
3678:
  lat: 50.12
  lon: -97.17
  name: STONY MOUNTAIN
  province: Manitoba
3766:
  lat: 52.03
  lon: -100.65
  name: COWAN
  province: Manitoba
8993:
  lat: 51.08
  lon: -97.55
  name: FISHER BRANCH (AUT)
  province: Manitoba
10186:
  lat: 50.18
  lon: -96.06
  name: PINAWA
  province: Manitoba
10188:
  lat: 52.11
  lon: -101.23
  name: SWAN RIVER RCS
  province: Manitoba
10196:
  lat: 49.02
  lon: -95.6
  name: SPRAGUE
  province: Manitoba
10225:
  lat: 51.67
  lon: -110.21
  name: ESTHER 1
  province: Alberta
10727:
  lat: 52.82
  lon: -104.6
  name: MELFORT
  province: Saskatchewan
10784:
  lat: 51.57
  lon: -107.92
  name: ROSETOWN EAST
  province: Saskatchewan
10884:
  lat: 49.9
  lon: -98.28
  name: PORTAGE SOUTHPORT
  province: Manitoba
10906:
  lat: 52.45
  lon: -113.76
  name: LACOMBE CDA 2
  province: Alberta
10915:
  lat: 49.73
  lon: -111.45
  name: BOW ISLAND
  province: Alberta
27741:
  lat: 49.91
  lon: -99.36
  name: CARBERRY CS
  province: Manitoba
